/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_imageprocessing;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Quchi
 */
public class OknoGłówneProgramu extends javax.swing.JFrame {
 
    private WybórPliku WybórPliku;
    /**
     * Creates new form OknoGłównePorgramu
     */
    public OknoGłówneProgramu() {
        super ("Projekt Programowanie Współbierzne ");
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        setLocation(width/4, height/4);
        setVisible(true);
    }
    public String PobierzSciezke(){
        return WybórPliku.PobierzScieżkę();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        Wyświetlacz = new javax.swing.JPanel();
        ButtonWybórFolderu = new javax.swing.JButton();
        ButtonWybórPliku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelWyświetlWybranyPlik = new javax.swing.JLabel();
        LabelWyświetlWybranyFolder = new javax.swing.JLabel();
        LiczbaWątków = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ButtonPrzetwozenieObrazu = new javax.swing.JButton();
        ButtonPrzetworzenieZbioruObrazu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout WyświetlaczLayout = new javax.swing.GroupLayout(Wyświetlacz);
        Wyświetlacz.setLayout(WyświetlaczLayout);
        WyświetlaczLayout.setHorizontalGroup(
            WyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        WyświetlaczLayout.setVerticalGroup(
            WyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        ButtonWybórFolderu.setText("WybórFolderu");
        ButtonWybórFolderu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWybórFolderuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonWybórFolderuMousePressed(evt);
            }
        });

        ButtonWybórPliku.setText("WybórPliku");
        ButtonWybórPliku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWybórPlikuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonWybórPlikuMousePressed(evt);
            }
        });

        jLabel1.setText("Wybrany Plik: ");

        jLabel2.setText("Wybrany Folder: ");

        LabelWyświetlWybranyPlik.setText("Wybierz Plik");

        LabelWyświetlWybranyFolder.setText("Wybierz Folder");

        String[] Watek = new String[60];
        for(int watek = 0 ; watek < 60 ;watek ++)
        {
            Watek[watek]=String.valueOf(watek+1);
        }
        LiczbaWątków.setModel(new javax.swing.DefaultComboBoxModel<>(Watek));

        jLabel5.setText("Ustawienie Liczby wątków:");

        ButtonPrzetwozenieObrazu.setText("Przetwórz pojedyńczy obraz");
        ButtonPrzetwozenieObrazu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPrzetwozenieObrazuMouseClicked(evt);
            }
        });

        ButtonPrzetworzenieZbioruObrazu.setText("Przetwórz zbiór obrazów");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Wyświetlacz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonPrzetworzenieZbioruObrazu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPrzetwozenieObrazu, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(ButtonWybórPliku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonWybórFolderu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LiczbaWątków, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelWyświetlWybranyPlik)
                            .addComponent(LabelWyświetlWybranyFolder))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LiczbaWątków, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonWybórPliku)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonWybórFolderu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPrzetwozenieObrazu)
                    .addComponent(jLabel1)
                    .addComponent(LabelWyświetlWybranyPlik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPrzetworzenieZbioruObrazu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(LabelWyświetlWybranyFolder))
                .addGap(34, 34, 34)
                .addComponent(Wyświetlacz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonWybórPlikuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórPlikuMousePressed

    }//GEN-LAST:event_ButtonWybórPlikuMousePressed

    private void ButtonWybórFolderuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórFolderuMouseClicked
      WybórPliku = new  WybórPliku(Wybór.FOLDER);
      WybórPliku.setTitle("Wybierz Folder");
      LabelWyświetlWybranyFolder.setText(WybórPliku.PobierzScieżkę());
    }//GEN-LAST:event_ButtonWybórFolderuMouseClicked

    private void ButtonWybórPlikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórPlikuMouseClicked
      WybórPliku = new  WybórPliku(Wybór.PLIK);
      WybórPliku.setTitle("Wybierz Plik");
      LabelWyświetlWybranyPlik.setText(WybórPliku.PobierzScieżkę());
    }//GEN-LAST:event_ButtonWybórPlikuMouseClicked

    private void ButtonWybórFolderuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórFolderuMousePressed

    }//GEN-LAST:event_ButtonWybórFolderuMousePressed

    private void ButtonPrzetwozenieObrazuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrzetwozenieObrazuMouseClicked
     MainFrame mainFrame = new MainFrame(WybórPliku.PobierzPlik(),LiczbaWątków.getSelectedIndex()+1);

     mainFrame.processImage();   // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPrzetwozenieObrazuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoGłówneProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OknoGłówneProgramu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPrzetworzenieZbioruObrazu;
    private javax.swing.JButton ButtonPrzetwozenieObrazu;
    private javax.swing.JButton ButtonWybórFolderu;
    private javax.swing.JButton ButtonWybórPliku;
    private javax.swing.JLabel LabelWyświetlWybranyFolder;
    private javax.swing.JLabel LabelWyświetlWybranyPlik;
    private javax.swing.JComboBox<String> LiczbaWątków;
    private javax.swing.JPanel Wyświetlacz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
