/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_imageprocessing;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.ListModel;

/**
 *
 * @author Quchi
 */
public class OknoGłówneProgramu extends javax.swing.JFrame {
    MainFrame mainFrame;
    private WybórPliku WybórPliku;
    private final ImagePanel ImagePanel = new ImagePanel();
    Thread OknoPojedynczegoObrazu;
    ArrayList<String> Lista;
    /**
     * Creates new form OknoGłównePorgramu
     */
    public OknoGłówneProgramu() {
        super ("Projekt Programowanie Współbierzne ");
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        setLocation(width/4, height/4);
        setVisible(true);
    }
    
    public File getFile(String Sciezka){
        File File=  new File(Sciezka);
        return File ;
    }
    
    
    public ArrayList<String> ListaPlikówWFolderze(String Sciezka) throws IOException{
        ArrayList<String> ListaPlików = new ArrayList<>();
        try(Stream<Path> paths = Files.walk(Paths.get(Sciezka))) {
          paths.forEach((Path filePath) -> {
        if (Files.isRegularFile(filePath)) {
            ListaPlików.add(filePath.toString());
           }
          });
         }
        return ListaPlików;
    }
    
    public String PobierzSciezke(){
        return WybórPliku.PobierzScieżkę();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Wyświetlacz = ImagePanel;
        ButtonWybórFolderu = new javax.swing.JButton();
        ButtonWybórPliku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelWyświetlWybranyPlik = new javax.swing.JLabel();
        LabelWyświetlWybranyFolder = new javax.swing.JLabel();
        LiczbaWątków = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ButtonPrzetwozenieObrazu = new javax.swing.JButton();
        ButtonPrzetworzenieZbioruObrazu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaZdjęć = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout WyświetlaczLayout = new javax.swing.GroupLayout(Wyświetlacz);
        Wyświetlacz.setLayout(WyświetlaczLayout);
        WyświetlaczLayout.setHorizontalGroup(
            WyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        WyświetlaczLayout.setVerticalGroup(
            WyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        ButtonWybórFolderu.setText("WybórFolderu");
        ButtonWybórFolderu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWybórFolderuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonWybórFolderuMousePressed(evt);
            }
        });

        ButtonWybórPliku.setText("WybórPliku");
        ButtonWybórPliku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWybórPlikuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonWybórPlikuMousePressed(evt);
            }
        });

        jLabel1.setText("Wybrany Plik: ");

        jLabel2.setText("Wybrany Folder: ");

        LabelWyświetlWybranyPlik.setText("Wybierz Plik");

        LabelWyświetlWybranyFolder.setText("Wybierz Folder");

        String[] Watek = new String[60];
        for(int watek = 0 ; watek < 60 ;watek ++)
        {
            Watek[watek]=String.valueOf(watek+1);
        }
        LiczbaWątków.setModel(new javax.swing.DefaultComboBoxModel<>(Watek));

        jLabel5.setText("Ustawienie Liczby wątków:");

        ButtonPrzetwozenieObrazu.setText("Przetwórz pojedyńczy obraz");
        ButtonPrzetwozenieObrazu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPrzetwozenieObrazuMouseClicked(evt);
            }
        });

        ButtonPrzetworzenieZbioruObrazu.setText("Przetwórz zbiór obrazów");
        ButtonPrzetworzenieZbioruObrazu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPrzetworzenieZbioruObrazuMouseClicked(evt);
            }
        });

        ListaZdjęć.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Wybierz folder zawierające zdjęcia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaZdjęć.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaZdjęćMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaZdjęć);

        jLabel3.setText("Lista zdjęć w wybranym folderze (klikając na przykładową ścieżkę -  program przetwarza wybrany obraz) :");

        jLabel4.setText("Skala zdjęcia 1:1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ButtonWybórPliku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonWybórFolderu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPrzetwozenieObrazu, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPrzetworzenieZbioruObrazu, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LiczbaWątków, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelWyświetlWybranyPlik)
                            .addComponent(LabelWyświetlWybranyFolder)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wyświetlacz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonWybórFolderu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonWybórPliku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPrzetwozenieObrazu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPrzetworzenieZbioruObrazu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(LiczbaWątków, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelWyświetlWybranyFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelWyświetlWybranyPlik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wyświetlacz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonWybórPlikuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórPlikuMousePressed

    }//GEN-LAST:event_ButtonWybórPlikuMousePressed

    private void ButtonWybórFolderuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórFolderuMouseClicked
      WybórPliku = new  WybórPliku(Wybór.FOLDER);
      WybórPliku.setTitle("Wybierz Folder");
      LabelWyświetlWybranyFolder.setText(WybórPliku.PobierzScieżkę());
      Lista = null;
        try {
        Lista  = ListaPlikówWFolderze(LabelWyświetlWybranyFolder.getText());
        } catch (IOException ex) {
            Logger.getLogger(OknoGłówneProgramu.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] stringsa = Lista.toArray(new String[Lista.size()]) ;
        
        ListaZdjęć.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = stringsa;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
      // ListaZdjęć.setModel(Lista);
    }//GEN-LAST:event_ButtonWybórFolderuMouseClicked

    private void ButtonWybórPlikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórPlikuMouseClicked
      WybórPliku = new  WybórPliku(Wybór.PLIK);
      WybórPliku.setTitle("Wybierz Plik");
      LabelWyświetlWybranyPlik.setText(WybórPliku.PobierzScieżkę());
        try {
            ImagePanel.getImageFromFile(WybórPliku.PobierzPlik());
            ImagePanel.refresh();
        } catch (IOException ex) {
            Logger.getLogger(OknoGłówneProgramu.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
    }//GEN-LAST:event_ButtonWybórPlikuMouseClicked

    private void ButtonWybórFolderuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWybórFolderuMousePressed
         
        
    }//GEN-LAST:event_ButtonWybórFolderuMousePressed

    private void ButtonPrzetwozenieObrazuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrzetwozenieObrazuMouseClicked
        OknoPojedynczegoObrazu = new Thread(new MainFrameRunnable(new File(LabelWyświetlWybranyPlik.getText()),LiczbaWątków.getSelectedIndex()+1));
        OknoPojedynczegoObrazu.start();
    }//GEN-LAST:event_ButtonPrzetwozenieObrazuMouseClicked

    private void ButtonPrzetworzenieZbioruObrazuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPrzetworzenieZbioruObrazuMouseClicked
        for( int Zdjęcie = 0 ; Zdjęcie< ListaZdjęć.getWidth()-1 ;Zdjęcie++ )
        {
        LabelWyświetlWybranyPlik.setText(Lista.get(Zdjęcie));    
        OknoPojedynczegoObrazu = new Thread(new MainFrameRunnable(new File(LabelWyświetlWybranyPlik.getText()),LiczbaWątków.getSelectedIndex()+1));
        OknoPojedynczegoObrazu.start();  
        }
    }//GEN-LAST:event_ButtonPrzetworzenieZbioruObrazuMouseClicked

    private void ListaZdjęćMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaZdjęćMouseClicked
       
       // OknoPojedynczegoObrazu = new Thread(new MainFrameRunnable(new File(ListaZdjęć.getSelectedValue()),LiczbaWątków.getSelectedIndex()+1));
        //OknoPojedynczegoObrazu.start();
        LabelWyświetlWybranyPlik.setText(ListaZdjęć.getSelectedValue());
        try {
            ImagePanel.getImageFromFile(new File(ListaZdjęć.getSelectedValue()));
            ImagePanel.refresh();
        } catch (IOException ex) {
            Logger.getLogger(OknoGłówneProgramu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ListaZdjęćMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoGłówneProgramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OknoGłówneProgramu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPrzetworzenieZbioruObrazu;
    private javax.swing.JButton ButtonPrzetwozenieObrazu;
    private javax.swing.JButton ButtonWybórFolderu;
    private javax.swing.JButton ButtonWybórPliku;
    private javax.swing.JLabel LabelWyświetlWybranyFolder;
    private javax.swing.JLabel LabelWyświetlWybranyPlik;
    private javax.swing.JComboBox<String> LiczbaWątków;
    private javax.swing.JList<String> ListaZdjęć;
    private javax.swing.JPanel Wyświetlacz;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
