/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pw_imageprocessing;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author Quchi
 */
public class WybórPliku extends javax.swing.JFrame {

    /**
     * Creates new form WybórPliku
     */
    private String Scieżka;
    Wybór  Wybór;
    File file;
    public String PobierzScieżkę(){
      return Scieżka; 
    }
    
    public File PobierzPlik(){
        return file;
    }
    public BufferedImage PobierzObraz() throws IOException{
       return ImageIO.read(file);
    }
    public WybórPliku(Wybór Wybór) {
 
       this.Wybór=Wybór;
       int returnVal = 0;
       if (Wybór == Wybór.PLIK)
       {
         
          initComponents();
          JFileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY); 
          returnVal = JFileChooser.showOpenDialog(null);
         
       }
       else if(Wybór == Wybór.FOLDER){
          initComponents();
          returnVal = JFileChooser.showOpenDialog(null);
          
       }
       
       
       JFileChooser.approveSelection();
       if(returnVal == JFileChooser.APPROVE_OPTION){
         Scieżka =    JFileChooser.getSelectedFile().getAbsolutePath(); 
         file = JFileChooser.getSelectedFile();
       }
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       int width = (int) screenSize.getWidth();
       int height = (int) screenSize.getHeight();
       setLocation(width/4+200, height/4+100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        if(Wybór==Wybór.FOLDER){
            JFileChooser.setDialogTitle("Dokonaj wyboru folderu z obrazami");
        }
        else if(Wybór==Wybór.PLIK){
            JFileChooser.setDialogTitle("Dokonaj wyboru pliku z obrazem");
        }
        JFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Quchi\\Documents\\PW_ImageProcessing\\files"));
        JFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        JFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFileChooser;
    // End of variables declaration//GEN-END:variables
}
